name: wildfire-risk-index CI/CD Pipeline to using Docker Hub

# 워크플로우가 실행될 조건 (트리거)
on:
  push:
    branches: [ "main" ] # main 브랜치에 push 될 때 실행

# 실행될 작업(Job)들 정의
jobs:
  build-and-push:
    # 작업이 실행될 가상 환경
    runs-on: ubuntu-latest

    # 작업의 단계(Step)들
    steps:
      # 1. 레포지토리 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # 2단계에서 GitHub Secrets에 저장한 정보 사용
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Docker 이미지 빌드 및 Docker Hub에 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 이미지 태그 설정: DockerHubID/레포지토리이름:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest

 # ===== 여기부터 배포 작업 추가 =====
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest image on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Docker Hub에서 최신 이미지를 pull 받아 놓기만 한다.
            # 실행은 EC2의 Cron이 담당한다.
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
            
            # 2. GitHub Secrets의 값을 사용하여 EC2 서버에 .env 파일을 생성합니다.
            tee /home/ubuntu/.env <<EOF
            # 이 파일은 GitHub Actions에 의해 자동 생성됩니다.
            EXECUTION_ENV=production
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_PORT=${{ secrets.DB_PORT }}
            EOF